IF OBJECT_ID('TBL_SALES', 'U') IS NOT NULL
    DROP TABLE TBL_SALES;
IF OBJECT_ID('TBL_STOCK', 'U') IS NOT NULL
    DROP TABLE TBL_STOCK;
CREATE TABLE TBL_STOCK (
	Product_ID Varchar(6),
	Product_Name Varchar(20),
	Quantity_On_Hand int,
	Product_Unit_Price numeric(11,2),
	Reorder_Level int,
	CONSTRAINT PK00 PRIMARY KEY(Product_ID),
	CONSTRAINT UQ01 UNIQUE(Product_Name),
	CONSTRAINT CH02 CHECK(Quantity_On_Hand >= 0),
	CONSTRAINT CH03 CHECK(Product_Unit_Price >= 0),
	CONSTRAINT CH04 CHECK(Reorder_Level >= 0)
);

CREATE TABLE TBL_SALES (
	Sales_ID Varchar(6), 
	Sales_Date Date,
	Product_ID Varchar(6),
	Quantity_Sold int,
	Sales_Price_Per_Unit numeric(11,2),
	CONSTRAINT PK10 PRIMARY KEY(Sales_ID),
	CONSTRAINT FK11 FOREIGN KEY(Product_ID) REFERENCES TBL_STOCK(Product_ID),
	
	CONSTRAINT CH12 CHECK(Quantity_Sold >= 0),
	CONSTRAINT CH13 CHECK(Sales_Price_Per_Unit >= 0)
);

INSERT INTO TBL_STOCK VALUES('RE1001', 'REDMI Note 3', 20, 12000, 5);
INSERT INTO TBL_STOCK VALUES('ip1002', 'Iphone 5S', 10, 21000, 2);
INSERT INTO TBL_STOCK VALUES('PA1003', 'Panasonic P55', 50, 5500, 5);

IF OBJECT_ID('SEQ_SALES_ID', 'SO') IS NOT NULL
    DROP SEQUENCE SEQ_SALES_ID;
IF OBJECT_ID('SEQ_PRODUCT_ID', 'SO') IS NOT NULL
    DROP SEQUENCE SEQ_PRODUCT_ID;
CREATE SEQUENCE SEQ_SALES_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_ID START WITH 1004 INCREMENT BY 1;
	
CREATE VIEW V_SALES_REPORT AS
	SELECT TBL_SALES.Sales_ID, TBL_SALES.Sales_Date, TBL_SALES.Product_ID, TBL_STOCK.Product_Name, 
			TBL_SALES.Quantity_Sold, TBL_STOCK.Product_Unit_Price, TBL_SALES.Sales_Price_Per_Unit, 
			(TBL_SALES.Sales_Price_Per_Unit - TBL_STOCK.Product_Unit_Price) AS Profit_Amount
	FROM TBL_STOCK 
    JOIN TBL_SALES ON TBL_STOCK.Product_ID = TBL_SALES.Product_ID;
